Add startosis version of the module
kurtosis-tech/datastore-army-module pull request #32
Opened 2022-10-05 13:50 UTC by gbouv

The only thing that cannot be achieved right now is to pass in the number of services to start as params of the CLI. But this is something that can easily be tweaked by updating the `PARAM` section of the script before running it

2022-10-05 14:03 UTC, h4ck3rk3y approved these changes
This looks alright but how does this get executed at the moment, you clone this and run the cli on it? Or do we run an interpreter that loads this? Or will the go sdk call this module?

2022-10-05 14:03 UTC, h4ck3rk3y commented on kurtosis-module/impl/datastore_army_kurtosis_module.go
> +//
gofmt screw up

2022-10-05 14:03 UTC, h4ck3rk3y commented on startosis/datastore-army-module.star
> +    for i in range(num_datastores):
nit: s/i/index/g

2022-10-05 14:11 UTC, gbouv commented
Once the [CLI PR is merged](https://github.com/kurtosis-tech/kurtosis/pull/166), you will be able to run it with a simple:
```
kurtosis startosis exec datastore-army-module.star [--enclave-is datastore-army-module]
```

2022-10-05 18:33 UTC, h4ck3rk3y requested changes
needs a CHANGELOG entry, preferably breaking

2022-10-05 18:34 UTC, h4ck3rk3y commented
> Once the [CLI PR is merged](https://github.com/kurtosis-tech/kurtosis/pull/166), you will be able to run it with a simple:
> 
> ```
> kurtosis startosis exec datastore-army-module.star [--enclave-is datastore-army-module]
> ```

Oh so you clone it and then do it. Just UX doesn't have to be a part of this at all but what about something like kurtosis startosis exec github.com/path/to/main.star, that loads and executes the main function?

2022-10-05 22:14 UTC, mieubrisse approved these changes

2022-10-05 22:14 UTC, mieubrisse commented on startosis/datastore-army-module.star
> +            datastore_port_id: struct(number = datastore_port_number, protocol = "TCP")
Magic `TCP` constant

2022-10-05 22:14 UTC, mieubrisse commented on startosis/datastore-army-module.star
> +datastore_image = "kurtosistech/example-datastore-server"
Recommend using UPPER_SNAKE_CASE convention for constants (will be a good habit to get into as we get bigger scripts)

2022-10-05 22:15 UTC, mieubrisse commented on startosis/datastore-army-module.star
> +            datastore_port_id: struct(number = datastore_port_number, protocol = "TCP")
ideally this is an enum that Starlark easily provides (don't have to do for now though)

2022-10-07 08:01 UTC, gbouv commented on startosis/datastore-army-module.star
> +            datastore_port_id: struct(number = datastore_port_number, protocol = "TCP")
Yes we can interpret Starlark scripts "in an environment", in which we can put all sort of stuffs. We should start thinking of what a good "Startosis base environment" looks like. Alternatively, we can use modules.

2022-10-07 08:06 UTC, gbouv commented
@h4ck3rk3y yes we could add the execution of a script directly from GH, that'd be a FR :P
Added changelog, though I think Breaking is a bit too much here, we're not breaking anything of the current behaviour. I added a Feature for now. Once/When we remove the Go module code, we can do Breaking

2022-10-07 22:01 UTC, mieubrisse approved these changes
Good for me

2022-10-07 22:02 UTC, h4ck3rk3y approved these changes
Yalla @gbouv

2022-10-10 14:23 UTC, merged